services:
  # This container is not used in prod
  mongo:
    image: mongo:4.2.5
    container_name: mongo
    ports:
      - '27017:27017'

  backend:
    build: .
    container_name: backend
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      # JWT_SECRET_KEY is arbitrary
      - JWT_SECRET_KEY=ihavealongpassword
      - HOST=http://localhost:8080
    command: nodemon server.js