services:
  # MongoDB Service
  mongo:
    image: mongo:4.2.5
    container_name: mongo
    ports:
      - '27017:27017'
#    volumes:
#      - mongo-data:/data/db

  # Backend Service (Express/Node.js)
  backend:
    build: .
    container_name: backend
    ports:
      - '8080:8080'
    depends_on:
      - mongo
#    environment:
#      - MONGO_URI=mongodb://mongo:27017/
#    volumes:
#      - ./backend:/app
#      - /app/node_modules
    command: nodemon server.js

#  # Frontend Service (React.js)
#  frontend:
#    build:
#      context: ./frontend
#    container_name: frontend
#    ports:
#      - '8080:8080'
#    depends_on:
#      - backend
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
#    stdin_open: true
#    tty: true
#
#volumes:
#  mongo-data:
